# Generated by Django 4.2.7 on 2026-07-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="last_sync_attempt",
            field=models.DateTimeField(
                blank=True,
                help_text="When synchronization was last attempted.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="last_sync_error",
            field=models.TextField(
                blank=True,
                help_text="Error message from the last failed synchronization.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="supermemory_document_id",
            field=models.CharField(
                blank=True,
                help_text="The document ID returned by Supermemory Local.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                help_text="Status of synchronization with Supermemory.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this memory was successfully synchronized.",
                null=True,
            ),
        ),
    ]
