# Generated by Django 4.2.7 on 2026-07-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0002_memory_last_sync_attempt_memory_last_sync_error_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="memory",
            name="idx_memory_user_status",
        ),
        migrations.RemoveField(
            model_name="memory",
            name="status",
        ),
        migrations.AddField(
            model_name="memory",
            name="ai_last_error",
            field=models.TextField(
                blank=True,
                help_text="Error message from the last failed AI enrichment.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="ai_processed_at",
            field=models.DateTimeField(
                blank=True, help_text="When AI enrichment was completed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="ai_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="memory",
            index=models.Index(
                fields=["user", "ai_status"], name="idx_memory_user_status"
            ),
        ),
    ]
