# Generated by Django 4.2.7 on 2026-07-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0004_memory_type_url_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="link_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User-provided custom title for LINK memories.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="link_url",
            field=models.URLField(
                blank=True,
                help_text="URL field for LINK memories (V2 requirement).",
                null=True,
            ),
        ),
    ]
