# Generated by Django 4.2.7 on 2026-07-22 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0005_memory_link_title_memory_link_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="raw_content",
            field=models.TextField(
                help_text="The user's unprocessed input. Max 5000 characters.",
                validators=[django.core.validators.MaxLengthValidator(5000)],
            ),
        ),
    ]
