# Generated by Django 4.2.7 on 2026-07-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0006_alter_memory_raw_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkMetadataCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("normalized_url", models.URLField(max_length=2000)),
                ("metadata_json", models.JSONField(default=dict)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "link metadata cache",
                "verbose_name_plural": "link metadata caches",
            },
        ),
        migrations.AddField(
            model_name="memory",
            name="author",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="memory",
            name="canonical_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="memory",
            name="capture_intent",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="memory",
            name="content_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="memory",
            name="favicon_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="memory",
            name="metadata_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="memory",
            name="page_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="memory",
            name="page_title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="memory",
            name="platform",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="memory",
            name="reading_time",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="memory",
            name="site_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="memory",
            name="source_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="memory",
            name="summary_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memory",
            name="summary_user_modified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memory",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="memory",
            name="tags_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memory",
            name="tags_user_modified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memory",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="memory",
            name="title_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memory",
            name="title_user_modified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="memory",
            name="ai_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("platform_detection", "Platform Detection"),
                    ("metadata_extraction", "Metadata Extraction"),
                    ("ai_enrichment", "AI Enrichment"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=25,
            ),
        ),
    ]
