# Generated by Django 4.2.7 on 2026-07-29 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "memories",
            "0007_linkmetadatacache_memory_author_memory_canonical_url_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingCapture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "capture_type",
                    models.CharField(
                        help_text="e.g. 'link', 'dump', 'code'", max_length=50
                    ),
                ),
                ("payload_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("version", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "pending capture",
                "verbose_name_plural": "pending captures",
            },
        ),
    ]
