# Generated by Django 4.2.7 on 2026-07-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0008_pendingcapture"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="pinned_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp when memory was pinned, or null if unpinned.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="memory",
            index=models.Index(
                fields=["user", "-pinned_at"], name="idx_memory_user_pinned"
            ),
        ),
    ]
