# Generated by Django 4.2.7 on 2026-07-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0008_pendingcapture"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="capture_source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("WEB_SHARE", "Web Share"),
                    ("ANDROID_SHARE", "Android Share"),
                    ("EXTENSION", "Extension"),
                    ("IMPORT", "Import"),
                    ("API", "API"),
                ],
                db_index=True,
                default="MANUAL",
                help_text="Originating source of this memory capture.",
                max_length=20,
            ),
        ),
    ]
