# Generated by Django 4.2.7 on 2026-07-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0009_memory_pinned_at_memory_idx_memory_user_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="share_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Cryptographically secure token for public knowledge sharing.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="shared_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when sharing was enabled or regenerated.",
                null=True,
            ),
        ),
    ]
