# Generated by Django 4.2.7 on 2026-07-31 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0009_memory_capture_source"),
        ("memories", "0010_memory_share_token_memory_shared_at"),
    ]

    operations = []
