from rest_framework import serializers

from apps.memories.models import Memory


class CaptureSerializer(serializers.Serializer):
    """
    Write-only serializer for capturing a memory.

    Accepts only raw_content — the user's unprocessed thought.
    Everything else (title, summary, embedding) is generated by AI.
    """

    raw_content = serializers.CharField(
        max_length=5000,
        error_messages={
            "max_length": "Memory exceeds the maximum size of 5000 characters."
        }
    )
    link_title = serializers.CharField(max_length=255, required=False, allow_blank=True)

    def validate_raw_content(self, value: str) -> str:
        if len(value) > 5000:
            raise serializers.ValidationError("Memory exceeds the maximum size of 5000 characters.")
        return value

    def create(self, validated_data: dict) -> Memory:
        """Delegate to the capture service."""
        from apps.memories.services.capture_service import capture_memory

        user = self.context["request"].user
        return capture_memory(
            user=user, 
            raw_content=validated_data["raw_content"],
            link_title=validated_data.get("link_title", "")
        )


class MemoryReadSerializer(serializers.ModelSerializer):
    """
    Read-only serializer for returning memory data.

    Includes both the raw content, AI-generated metadata,
    and content-type fields (memory_type, url, domain).
    """

    class Meta:
        model = Memory
        fields = [
            "id",
            "memory_type",
            "raw_content",
            "url",
            "domain",
            "link_url",
            "link_title",
            "ai_title",
            "ai_summary",
            "ai_status",
            "created_at",
            "updated_at",
        ]
        read_only_fields = fields

class MemoryUpdateSerializer(serializers.ModelSerializer):
    """
    Serializer for updating specific fields of a memory.
    Supports:
      - link_title: user-defined title for any memory
      - raw_content: allows editing the memory's content directly
    """
    class Meta:
        model = Memory
        fields = ["link_title", "raw_content"]
