from rest_framework import serializers

from apps.memories.models import Memory


class CaptureSerializer(serializers.Serializer):
    """
    Write-only serializer for capturing a memory.

    Accepts only raw_content — the user's unprocessed thought.
    Everything else (title, summary, embedding) is generated by AI.
    """

    raw_content = serializers.CharField()

    def create(self, validated_data: dict) -> Memory:
        """Delegate to the capture service."""
        from apps.memories.services import capture_memory

        user = self.context["request"].user
        return capture_memory(user=user, raw_content=validated_data["raw_content"])


class MemoryReadSerializer(serializers.ModelSerializer):
    """
    Read-only serializer for returning memory data.

    Includes both the raw content, AI-generated metadata,
    and content-type fields (memory_type, url, domain).
    """

    class Meta:
        model = Memory
        fields = [
            "id",
            "memory_type",
            "raw_content",
            "url",
            "domain",
            "ai_title",
            "ai_summary",
            "ai_status",
            "created_at",
            "updated_at",
        ]
        read_only_fields = fields
