from rest_framework import serializers

from apps.memories.models import Memory


class CaptureSerializer(serializers.Serializer):
    """
    Write-only serializer for capturing a memory.

    Accepts only raw_content — the user's unprocessed thought.
    Everything else (title, summary, embedding) is generated by AI.
    """

    raw_content = serializers.CharField(
        max_length=5000,
        error_messages={
            "max_length": "Memory exceeds the maximum size of 5000 characters."
        }
    )
    link_title = serializers.CharField(max_length=255, required=False, allow_blank=True)
    preview_id = serializers.UUIDField(required=False, allow_null=True)
    is_pinned = serializers.BooleanField(required=False, default=False)
    capture_source = serializers.ChoiceField(
        choices=Memory.CaptureSource.choices,
        required=False,
        default=Memory.CaptureSource.MANUAL
    )

    def validate_raw_content(self, value: str) -> str:
        if len(value) > 5000:
            raise serializers.ValidationError("Memory exceeds the maximum size of 5000 characters.")
        return value

    def create(self, validated_data: dict) -> Memory:
        """Delegate to the capture service."""
        from apps.memories.services.capture_service import capture_memory

        user = self.context["request"].user
        return capture_memory(
            user=user, 
            raw_content=validated_data["raw_content"],
            link_title=validated_data.get("link_title", ""),
            preview_id=validated_data.get("preview_id"),
            is_pinned=validated_data.get("is_pinned", False),
            capture_source=validated_data.get("capture_source", Memory.CaptureSource.MANUAL),
        )


class MemoryReadSerializer(serializers.ModelSerializer):
    """
    Read-only serializer for returning memory data.

    Includes both the raw content, AI-generated metadata,
    and content-type fields (memory_type, url, domain).
    """

    is_pinned = serializers.BooleanField(read_only=True)

    class Meta:
        model = Memory
        fields = [
            "id",
            "memory_type",
            "capture_source",
            "is_pinned",
            "raw_content",
            "url",
            "domain",
            "link_url",
            "link_title",
            "ai_title",
            "ai_summary",
            "ai_status",
            "platform",
            "content_type",
            "source_url",
            "canonical_url",
            "page_title",
            "page_description",
            "favicon_url",
            "thumbnail_url",
            "site_name",
            "author",
            "reading_time",
            "metadata_json",
            "tags",
            "title_user_modified",
            "summary_user_modified",
            "tags_user_modified",
            "capture_intent",
            "title_confidence",
            "summary_confidence",
            "tags_confidence",
            "pinned_at",
            "is_pinned",
            "created_at",
            "updated_at",
        ]
        read_only_fields = fields

class MemoryUpdateSerializer(serializers.ModelSerializer):
    """
    Serializer for updating specific fields of a memory.
    Supports:
      - link_title: user-defined title for any memory
      - raw_content: allows editing the memory's content directly
    """
    class Meta:
        model = Memory
        fields = ["link_title", "raw_content", "ai_title", "ai_summary", "tags", "capture_intent"]
        
    def update(self, instance, validated_data):
        if "ai_title" in validated_data:
            instance.title_user_modified = True
        if "ai_summary" in validated_data:
            instance.summary_user_modified = True
        if "tags" in validated_data:
            instance.tags_user_modified = True
        return super().update(instance, validated_data)


class SharedMemorySerializer(serializers.ModelSerializer):
    """
    Public read-only serializer for shared memories.

    EXPLICIT PRIVACY GUARANTEE:
    Exposes ONLY:
      - title
      - summary (ai_summary)
      - content (raw_content)
      - created_at
      - memory_type
      - source_link

    NEVER exposes user IDs, owner info, internal DB primary keys,
    sync status, or private metadata.
    """

    title = serializers.SerializerMethodField()
    summary = serializers.CharField(source="ai_summary", read_only=True)
    content = serializers.CharField(source="raw_content", read_only=True)
    source_link = serializers.SerializerMethodField()

    class Meta:
        model = Memory
        fields = [
            "title",
            "summary",
            "content",
            "created_at",
            "memory_type",
            "source_link",
        ]
        read_only_fields = fields

    def get_title(self, obj: Memory) -> str:
        if obj.link_title:
            return obj.link_title
        if obj.ai_title:
            return obj.ai_title
        if obj.page_title:
            return obj.page_title
        # Fallback to truncated raw content if no title exists
        content = obj.raw_content.strip()
        return content[:60] + "..." if len(content) > 60 else content

    def get_source_link(self, obj: Memory) -> str:
        return obj.link_url or obj.url or obj.source_url or ""

